/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';


export namespace Components {

  interface WsHome {}
  interface WsHomeAttributes extends StencilHTMLAttributes {}

  interface WsHeader {}
  interface WsHeaderAttributes extends StencilHTMLAttributes {}

  interface WsNav {}
  interface WsNavAttributes extends StencilHTMLAttributes {}

  interface WsRoot {}
  interface WsRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'WsHome': Components.WsHome;
    'WsHeader': Components.WsHeader;
    'WsNav': Components.WsNav;
    'WsRoot': Components.WsRoot;
  }

  interface StencilIntrinsicElements {
    'ws-home': Components.WsHomeAttributes;
    'ws-header': Components.WsHeaderAttributes;
    'ws-nav': Components.WsNavAttributes;
    'ws-root': Components.WsRootAttributes;
  }


  interface HTMLWsHomeElement extends Components.WsHome, HTMLStencilElement {}
  var HTMLWsHomeElement: {
    prototype: HTMLWsHomeElement;
    new (): HTMLWsHomeElement;
  };

  interface HTMLWsHeaderElement extends Components.WsHeader, HTMLStencilElement {}
  var HTMLWsHeaderElement: {
    prototype: HTMLWsHeaderElement;
    new (): HTMLWsHeaderElement;
  };

  interface HTMLWsNavElement extends Components.WsNav, HTMLStencilElement {}
  var HTMLWsNavElement: {
    prototype: HTMLWsNavElement;
    new (): HTMLWsNavElement;
  };

  interface HTMLWsRootElement extends Components.WsRoot, HTMLStencilElement {}
  var HTMLWsRootElement: {
    prototype: HTMLWsRootElement;
    new (): HTMLWsRootElement;
  };

  interface HTMLElementTagNameMap {
    'ws-home': HTMLWsHomeElement
    'ws-header': HTMLWsHeaderElement
    'ws-nav': HTMLWsNavElement
    'ws-root': HTMLWsRootElement
  }

  interface ElementTagNameMap {
    'ws-home': HTMLWsHomeElement;
    'ws-header': HTMLWsHeaderElement;
    'ws-nav': HTMLWsNavElement;
    'ws-root': HTMLWsRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
